FROM python:3.10-slim

# 시스템 도구 설치
RUN apt update && apt install -y curl sqlite3 git

# MLflow 설치
RUN pip install mlflow[extras] scikit-learn

# 작업 디렉토리
WORKDIR /mlflow

CMD ["mlflow", "server", \
     "--backend-store-uri=sqlite:///mlflow.db", \
     "--default-artifact-root=/mlflow/artifacts", \
     "--host=0.0.0.0", \
     "--port=5000", \
     "--serve-artifacts"]
