FROM python:3.10-slim

# 작업 디렉토리 설정
WORKDIR /app

# 앱 디렉토리 복사
COPY app /app/app

# 의존성 설치
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install -r /app/requirements.txt

# FastAPI 앱 실행 (uvicorn)
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
