version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile.airflow
    container_name: airflow
    command: standalone
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
      AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES}
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./ml_code:/opt/airflow/ml_code
      - ./mlflow_store:/mlflow

  mlflow:
    build:
      context: ./mlflow_store
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_store:/mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile.api
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi/app:/app/app
      - ./ml_code:/app/ml_code
      - ./mlflow_store:/mlflow

volumes:
  postgres_data:
